"""
Django settings for bnb_7_cl project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from django.utils.encoding import force_bytes, force_str
from django.core.mail import send_mail
#import chatterbot
#from chatbot.adapters.word_block_adapter import word_block_adapter
#from chatbot.adapters.reply_change_adapter import reply_change_adapter

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = Path(__file__).resolve().parent.parent

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = force_str(os.environ.get('SECRET_KEY'))

#google api key
#GENERATIVE_AI_KEY = force_str(os.environ.get('GENERATIVE_AI_KEY')) # Don't forget to import os package
#if not GENERATIVE_AI_KEY:
#    raise ValueError('GENERATIVE_AI_KEY environment variable not set')

CSRF_TRUSTED_ORIGINS=['https://www.bytesnbytes.com']
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['bytsnbytes.com','www.bytsnbytes.com','localhost','138.68.76.165','postfixadmin.bytsnbytes.com']

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #chatterbot
    'chatterbot.ext.django_chatterbot',
    #INSTALLED APPS
    'website.apps.WebsiteConfig',
    'ms_oracle.apps.MsOracleConfig',
    'blog.apps.BlogConfig',
    'ecommerce.apps.EcommerceConfig',
    #'web_dev.apps.WebDevConfig',
    'freelance.apps.FreelanceConfig',
    #'chatbot.apps.ChatbotConfig',
    'guardian_download.apps.GuardianDownloadConfig',
    'portfolio.apps.PortfolioConfig',
    #'Chatbot_2.apps.Chatbot2Config',
    'chatbot_3.apps.Chatbot3Config',
    'image_generator',
    'threshold',
    'music_player_app',
    'api',
    'compressor',
    'captcha',
    'rest_framework',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.sites.middleware.CurrentSiteMiddleware',
]

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

CORS_ALLOWED_ORIGINS = [
    'https://144.86.9.125.com','https://sendgrid.com','https://www.bytsnbytes.com','https://saavn.dev',
]
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'VIEW',
)
CORS_ALLOW_HEADERS = (
    'XMLHttpRequest',
    'X_FILENAME',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'Pragma',
)


#security
#clickjack
#X_FRAME_OPTIONS = 'DENY'
CSRF_USE_SESSIONS = False

#csrf
CSRF_TRUSTED_ORIGINS = ["https://bytsnbytes.com", "https://www.bytsnbytes.com",'https://144.86.53.11:50004/webhooks/rest/webhook','https://saavn.dev',]
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_COOKIE_HTTPONLY = False

#rest framework (for chatterbot)
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}
#messages configuration
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}

AUTH_USER_MODEL = "ecommerce.EcomCustomer"


ROOT_URLCONF = 'bnb_7_cl.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['Templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ecommerce.context_processors.menu_links',
                'ecommerce.context_processors.service_menu_links',
                'ecommerce.context_processors.cart_count',
                'website.context_processors.current_news',

            ],
	'libraries' : {
		'staticfiles': 'django.templatetags.static',
		},
        },
    },
]

WSGI_APPLICATION = 'bnb_7_cl.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'byb_storage',
        'USER': 'mo_admin',
        'PASSWORD': 'buddhowab1ll123!',
        'HOST': '',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/


#STATIC_URL = 'static/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

STATICFILES_DIRS = [
   # os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR,'gallery'),
    '/home/atlass/bb_1/bnb_7_cl/store_gallery',
    '/home/atlass/bb_1/bnb_7_cl/service_gallery',

]

LOGIN_URL = 'user_login'

#email settings
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'localhost'
#EMAIL_USE_TLS = True
#EMAIL_PORT = 25 #587
#EMAIL_HOST_USER = 'admin@bytsnbytes.com' #sender's email-id
#EMAIL_HOST_PASSWORD = 'buddhowab1ll123!' #password associated with above email-id

#COINBASE
COINBASE_COMMERCE_API_KEY = '7b8a2989-0673-462c-a24d-a749f89470e0'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#for SASS
COMPRESS_PRECOMPILERS = (
    ('text/x-scss', 'django_libsass.SassCompiler'),
)

#compressor
STATICFILES_FINDERS =( 
    'django.contrib.staticfiles.finders.FileSystemFinder',  
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',    
    'compressor.finders.CompressorFinder',
)
COMPRESS_ROOT=str(STATIC_ROOT)

# SMTP configuration
#EMAIL_HOST = config('smtp.')
#EMAIL_PORT = config('EMAIL_PORT', cast=int)
#EMAIL_HOST_USER = config('EMAIL_HOST_USER')
#EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
#EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool)

#keys and constants
SENDGRID_API_KEY='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'

#CHATTERBOT
CHATTERBOT = {
    'name': 'Tech Support Bot',
    'logic_adapters': [
        'chatterbot.logic.MathematicalEvaluation',
        'chatterbot.logic.TimeLogicAdapter',
        'chatterbot.logic.BestMatch'
    ]
}
